### ISSUE TITLE
Notify restart handler after new files copied/template

### ISSUE THREAD

**Issue by jnogol** [idealista/tomcat-role#4]
In `config.yml`, lines [16](https://github.com/idealista/tomcat-role/blob/master/tasks/config.yml#L16) and [26](https://github.com/idealista/tomcat-role/blob/master/tasks/config.yml#L26), if there's any change, they don't notify the restart handler. This should be changed, as any new configuration should restart (or maybe just reload) the server.

**Comment by sorobon** [comment]
fixed in 1.7.0
