### ISSUE TITLE
Download and rename war before copy to webapps

### ISSUE THREAD

**Issue by jdvr** [idealista/tomcat-role#5]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

 During deploy the role downloads a war and copy it to webapps folder without modifying the name. This is is a problem because some projects wars name usually includes other information like profile or version that should be remove when copied to webapps

**Expected behavior:** 
The role should be able to process a list of war urls with a destination name. Download the war and copy it to webapps with desire destination name.

**Comment by dortegau** [comment]
Thinking of this issue I prefer to exclude the deploy tasks in other role. In my opinion isn't part of the responsability of this playbook. 

You could prefer to deploy a war...

- Using scp
- Using rsync
- Using NFS
- Using (S)FTP

We are restricting the war deployments and force to be exposed using an HTTP server. I think that this should be considered.

**Comment by jdvr** [comment]
I think deploy is a basic step of any tomcat configuration, Does it make sense to install/configure a tomcat without any war?

The role allows you to deploy using either a remote war url or copy from control machine to target machine. From my point of view having this options of deploy is a useful feature on this kind of services
